package.path="ue4ss/Mods/RoweModGameplay/Scripts/?.lua;"..package.path
local store=require("menu_store")
local values=store.decode("speedMultiplier=1.25\ntriggerSteering=false\nstreamlinedControls=true\nunknown=12\nmaxSpinSpeed=math.huge\njumpVelocity=1e999\nslomoSpeed=-1\n")
assert(values.speedMultiplier==1.25)
assert(values.triggerSteering==false and values.streamlinedControls==true)
assert(values.unknown==nil and values.maxSpinSpeed==nil and values.jumpVelocity==nil and values.slomoSpeed==0.25)
local migrated=store.decode("minJumpHeight=3000\ngrindMagnetStrength=10000\nmaxFlipSpeed=1914.4\nspeedMultiplier=3.0675656795502\njumpPrepSteering=6.05855\nsteerMultiplier=1.53\nbalanceDriftIncrease=9.07\ncameraDistance=999\n")
assert(migrated.minJumpHeight==1 and migrated.grindMagnetStrength==0.8 and migrated.maxFlipSpeed==455)
assert(migrated.speedMultiplier==3.05 and migrated.jumpPrepSteering==6)
assert(migrated.steerMultiplier==nil and migrated.balanceDriftIncrease==nil and migrated.cameraDistance==nil)
assert(next(store.decode(string.rep("x",16385)))==nil)
store.path=function() return arg[1].."/settings.txt" end
assert(store.save(values))
local loaded=store.load()
assert(loaded.triggerSteering==false and loaded.speedMultiplier==1.25)
assert(store.save({speedMultiplier=1.5}))
assert(store.load().speedMultiplier==1.5 and store.load().triggerSteering==nil)
local f=assert(io.open(store.path()..".bak","rb"));assert(f:read("*a"):match("speedMultiplier=1.25"));f:close()
assert(store.save({grindMagnetStrength=10000, speedMultiplier=math.huge, maxSpinSpeed=2000}))
local safe=store.load()
assert(safe.grindMagnetStrength==0.8 and safe.speedMultiplier==nil and safe.maxSpinSpeed==nil)
assert(store.save({gravityMultiplier=0.531}))
assert(store.load().gravityMultiplier==0.55)
assert(store.decode("gravityMultiplier=0").gravityMultiplier==1)
print("settings validation, false toggles, roundtrip and last-save backup passed")
