-- Display labels and edit limits. A nil override means use the game's value.
return {
    {id="Movement", items={
        {"speedMultiplier","Speed multiplier",0.4,4,0.05},
        {"casualSpeedIncrease","Casual acceleration",0,20000,10},
        {"sprintSpeedIncrease","Sprint acceleration",0,20000,10},
        {"steerMultiplier","Steering multiplier",0,10,0.05},
        {"steeringStrengthSetting","Steering strength",0,10,0.05},
        {"triggerSteering","Trigger steering","bool"},
        {"streamlinedControls","Streamlined controls","bool"},
        {"forceFeedbackStrength","Controller vibration",0,2,0.05},
    }},
    {id="Tricks", items={
        {"jumpVelocity","Jump velocity",0,10000,25},
        {"minJumpHeight","Minimum jump height",0,3000,5},
        {"maxJumpHeight","Maximum jump height",0,10000,10},
        {"jumpPrepSteering","Jump preparation steering",0,10,0.05},
        {"maxSpinSpeed","Maximum spin speed",0,5000,10},
        {"maxFlipSpeed","Maximum flip speed",0,5000,10},
        {"spinMultiplier","Spin multiplier",0,10,0.05},
        {"flipMultiplier","Flip multiplier",0,10,0.05},
        {"grabSpinSpeedDivider","Grab spin divider",0.1,20,0.1},
    }},
    {id="Balance", items={
        {"grindMagnetStrength","Grind magnet strength",0,10000,5},
        {"grindMagnetSize","Grind magnet size",0,1000,5},
        {"balanceIntensity","Balance intensity",0,20,0.1},
        {"balanceDriftIncrease","Balance drift increase",0,20,0.1},
        {"balanceDriftStrength","Balance drift strength",0,20,0.1},
        {"baseBalanceDrift","Base balance drift",0,20,0.1},
        {"requiresBalance","Require balance","bool"},
        {"showBalanceMeter","Show balance meter","bool"},
        {"enableGrindSparks","Grind sparks","bool"},
    }},
    {id="Camera", items={
        {"cameraDistance","Camera distance",0,2000,10},
        {"cameraHeight","Camera height",-500,1000,5},
        {"cameraLookUp","Camera look-up",-500,1000,5},
        {"cameraSideOffset","Camera side offset",-500,500,5},
        {"airRotInterpSpeed","Air rotation smoothing",0,50,0.5},
        {"slomoSpeed","Slow-motion speed",0.05,1,0.05},
        {"slowmotion","Slow motion","bool"},
    }},
}
